### ISSUE TITLE
Cannot build with GHC 9.4

### ISSUE THREAD

**Issue by ocharles** [haskell-primitive/primitive-unlifted#32]
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/fcxwrx8cb7dyax9jdx6p5xiy7z905xp3-primitive-unlifted-1.0.0.0.tar.gz
source root is primitive-unlifted-1.0.0.0
setting SOURCE_DATE_EPOCH to timestamp 1000000000 of file primitive-unlifted-1.0.0.0/test/Main.hs
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
Configure flags:
--prefix=/nix/store/5vdngx26qdi9x7gma7vjbdsps4zrjxgm-primitive-unlifted-lib-primitive-unlifted-1.0.0.0 lib:primitive-unlifted --package-db=clear --package-db=/nix/store/z06mzk5inq6qq166x4z5ipbllsihwhar-primitive-unlifted-lib-primitive-unlifted-1.0.0.0-config/lib/ghc-9.4.3/lib/package.conf.d --exact-configuration --dependency=primitive=primitive-0.7.4.0-F0fP468f3Bl6qhcpC3mefe --dependency=text-short=text-short-0.1.5-IBP1E3wNW8pB95sdRB3Lm4 --dependency=array=array-0.5.4.0 --dependency=base=base-4.17.0.0 --dependency=binary=binary-0.8.9.1 --dependency=bytestring=bytestring-0.11.3.1 --dependency=containers=containers-0.6.6 --dependency=deepseq=deepseq-1.4.8.0 --dependency=directory=directory-1.3.7.1 --dependency=exceptions=exceptions-0.10.5 --dependency=filepath=filepath-1.4.2.2 --dependency=ghc=ghc-9.4.3 --dependency=ghc-bignum=ghc-bignum-1.3 --dependency=ghc-boot=ghc-boot-9.4.3 --dependency=ghc-boot-th=ghc-boot-th-9.4.3 --dependency=ghc-compact=ghc-compact-0.1.0.0 --dependency=ghc-heap=ghc-heap-9.4.3 --dependency=ghc-prim=ghc-prim-0.9.0 --dependency=hpc=hpc-0.6.1.0 --dependency=integer-gmp=integer-gmp-1.1 --dependency=mtl=mtl-2.2.2 --dependency=parsec=parsec-3.1.15.0 --dependency=pretty=pretty-1.1.3.6 --dependency=process=process-1.6.16.0 --dependency=rts=rts-1.0.2 --dependency=stm=stm-2.5.1.0 --dependency=template-haskell=template-haskell-2.19.0.0 --dependency=terminfo=terminfo-0.4.1.5 --dependency=text=text-2.0.1 --dependency=time=time-1.12.2 --dependency=transformers=transformers-0.5.6.2 --dependency=unix=unix-2.7.3 --dependency=xhtml=xhtml-3000.2.2.1 --with-ghc=ghc --with-ghc-pkg=ghc-pkg --with-hsc2hs=hsc2hs --with-gcc=cc --with-ld=ld.gold --ghc-option=-optl-fuse-ld=gold --ld-option=-fuse-ld=gold --with-ar=ar --with-strip=strip --enable-executable-stripping --enable-library-stripping --enable-library-profiling --disable-profiling --enable-static --enable-shared --disable-coverage --enable-library-for-ghci --datadir=/nix/store/d9pa0909bm0g51ackdb84p2a7yypybpp-primitive-unlifted-lib-primitive-unlifted-1.0.0.0-data/share/ghc-9.4.3 --profiling-detail=default --enable-split-sections 
Configuring library for primitive-unlifted-1.0.0.0..
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Preprocessing library for primitive-unlifted-1.0.0.0..
Building library for primitive-unlifted-1.0.0.0..
[ 1 of 18] Compiling Data.Primitive.Unlifted.Array.Primops ( src/Data/Primitive/Unlifted/Array/Primops.hs, dist/build/Data/Primitive/Unlifted/Array/Primops.o, dist/build/Data/Primitive/Unlifted/Array/Primops.dyn_o )

src/Data/Primitive/Unlifted/Array/Primops.hs:45:25: error:
    Module ‘GHC.Exts’ does not export ‘RuntimeRep(UnliftedRep)’
   |
45 |                 , TYPE, RuntimeRep (UnliftedRep), unsafeCoerce#)
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^
[ 2 of 18] Compiling Data.Primitive.Unlifted.Class ( src/Data/Primitive/Unlifted/Class.hs, dist/build/Data/Primitive/Unlifted/Class.o, dist/build/Data/Primitive/Unlifted/Class.dyn_o )

src/Data/Primitive/Unlifted/Class.hs:27:18: error:
    Module ‘GHC.Exts’ does not export ‘RuntimeRep(UnliftedRep)’
   |
27 | import GHC.Exts (RuntimeRep(UnliftedRep))
   |                  ^^^^^^^^^^^^^^^^^^^^^^^
[ 7 of 18] Compiling Data.Primitive.Unlifted.MVar.Primops ( src/Data/Primitive/Unlifted/MVar/Primops.hs, dist/build/Data/Primitive/Unlifted/MVar/Primops.o, dist/build/Data/Primitive/Unlifted/MVar/Primops.dyn_o )

src/Data/Primitive/Unlifted/MVar/Primops.hs:24:36: error:
    Not in scope: data constructor ‘UnliftedRep’
    Suggested fix: Perhaps use ‘Unlifted’ (imported from GHC.Exts)
   |
24 | newtype UnliftedMVar# s (a :: TYPE 'UnliftedRep) = UnliftedMVar# (MVar# s Any)
   |                                    ^^^^^^^^^^^^
[10 of 18] Compiling Data.Primitive.Unlifted.MutVar.Primops ( src/Data/Primitive/Unlifted/MutVar/Primops.hs, dist/build/Data/Primitive/Unlifted/MutVar/Primops.o, dist/build/Data/Primitive/Unlifted/MutVar/Primops.dyn_o )

src/Data/Primitive/Unlifted/MutVar/Primops.hs:25:38: error:
    Not in scope: data constructor ‘UnliftedRep’
    Suggested fix: Perhaps use ‘Unlifted’ (imported from GHC.Exts)
   |
25 | newtype UnliftedMutVar# s (a :: TYPE 'UnliftedRep) = UnliftedMutVar# (MutVar# s Any)
   |                                      ^^^^^^^^^^^^
[13 of 18] Compiling Data.Primitive.Unlifted.SmallArray.Primops ( src/Data/Primitive/Unlifted/SmallArray/Primops.hs, dist/build/Data/Primitive/Unlifted/SmallArray/Primops.o, dist/build/Data/Primitive/Unlifted/SmallArray/Primops.dyn_o )

src/Data/Primitive/Unlifted/SmallArray/Primops.hs:47:70: error:
    Module ‘GHC.Exts’ does not export ‘RuntimeRep(UnliftedRep)’
   |
47 | import GHC.Exts (Int#,State#,SmallArray#,SmallMutableArray#,Any,TYPE,RuntimeRep(UnliftedRep),unsafeCoerce#)
   |                                                                      ^^^^^^^^^^^^^^^^^^^^^^^
[16 of 18] Compiling Data.Primitive.Unlifted.Weak.Primops ( src/Data/Primitive/Unlifted/Weak/Primops.hs, dist/build/Data/Primitive/Unlifted/Weak/Primops.o, dist/build/Data/Primitive/Unlifted/Weak/Primops.dyn_o )

src/Data/Primitive/Unlifted/Weak/Primops.hs:33:11: error:
    Module ‘GHC.Exts’ does not export ‘RuntimeRep(UnliftedRep)’
   |
33 |   ( TYPE, RuntimeRep (UnliftedRep), Any, unsafeCoerce#, RealWorld, State#
   |           ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by andrewthad** [comment]
`primitive-unlifted-1.0.0.0` is unsound and cannot be used with GHC 9.2 or GHC 9.4. `primitive-unlifted-0.1.3.1` is the version that works correctly. I can release a `primitve-unlifted-2.0.0.0` reverting everything if that makes things easier for the nixpkgs world.

**Comment by ocharles** [comment]
Thanks, I'll try adding a constraint to use < 1.0. Maybe 1.0 should be marked as deprecated to avoid Cabal choosing it in plans, or the bounds should be changed?

**Comment by andrewthad** [comment]
I've just now marked it as deprecated. If that doesn't work, I can also mess with the `base` bounds to make it unselectable by the solver.

**Comment by ocharles** [comment]
I've removed any workarounds I had before to build on GHC 9.4 and everything is happy. I'll go ahead and close this as fixed. Thanks!
