### ISSUE TITLE
testsuite fails to build with primitive-0.9

### ISSUE THREAD

**Issue by juhp** [haskell-primitive/primitive-unlifted#42]
```
       Building test suite 'test' for primitive-unlifted-2.1.0.0..                                                                  
       [1 of 1] Compiling Main [Test.QuickCheck package changed]                                                                    
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/primitive-unlifted-2.1.0.0-149a906c65c89f1a8fa73819f44d1b31a19b510525fcea8afb5114c67d
7c2cd5/test/Main.hs:58:32: error: [GHC-88464]                                                                                       
           Variable not in scope: fromList :: f0 a -> Array a                                                                       
          |                                                                                                                         
       58 |   liftArbitrary elemGen = fmap fromList (QC.liftArbitrary elemGen)                                                      
          |                                ^^^^^^^^                                                                                 
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/primitive-unlifted-2.1.0.0-149a906c65c89f1a8fa73819f44d1b31a19b510525fcea8afb5114c67d
7c2cd5/test/Main.hs:61:20: error: [GHC-88464]                                                                                       
           Variable not in scope: fromList :: a0 -> Array a                                                                         
          |                                                                                                                         
       61 |   arbitrary = fmap fromList QC.arbitrary                                                                                
          |                    ^^^^^^^^                                                                                             
curator: Received ExitFailure 1 when running
```

**Comment by andrewthad** [comment]
Fixed in 26922952ef20c4771d857f3e96c9e710cb3c2df9

**Comment by alaendle** [comment]
Thanks - re-enabled the test suite on stackage build - this issue can be closed.
